language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
gemfile:
  - gemfiles/rails_5.2.0.gemfile
  - gemfiles/rails_5.1.0.gemfile
  - gemfiles/rails_5.0.0.gemfile
  - gemfiles/rails_4.2.0.gemfile
notifications:
  email: false
sudo: false
